In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

SyntaxError: invalid non-printable character U+00A0 (2711481841.py, line 1)

In [2]:
import numpy as np

In [23]:
a = np.array(42)
b = np.array([1,2,3], dtype='int16')
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [5]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [7]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(2, 2, 3)


In [8]:
d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [10]:
arr = np.array([[1,2,3,4],[5,6,7,8]], dtype="int16")
print(arr.shape)

(2, 4)


In [14]:
a.itemsize

8

In [24]:
b.itemsize

2

In [26]:
b.dtype

dtype('int16')

In [27]:
b.size

3

In [28]:
b.size * b.itemsize

6

In [30]:
arr2 = np.array([1,2,3,4])

print(arr2.itemsize)

8


In [31]:
arr2.size

4

In [32]:
arr2.nbytes

32

In [33]:
array = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
array

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [34]:
array[0,5]

6

In [35]:
array[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
array[: , 2]

array([ 3, 10])

In [38]:
array[0, 1:6:2]

array([2, 4, 6])

In [39]:
array[1,5] = 20

In [40]:
array

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [59]:
array[:,2] 
array

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [44]:
array[:,2] = [1,2]
array

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [48]:
d2 = np.array([[[1,2],[3,4]],[[5,6],[8,9]]])

In [49]:
d2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [8, 9]]])

In [51]:
d2[0,0,1]

2

In [58]:
d2[:,1,:] = [[0,0],[1,1]]
d2

array([[[1, 2],
        [0, 0]],

       [[5, 6],
        [1, 1]]])